    <div class="row">
      <div id="content" class="col-lg-12">

<!-- LES ABSENCES DE MON/MES EQUIPE --> 
        <div class="box">
          <div class="box-header" data-original-title>
            <h2><i class="fa fa-users"></i><span class="break"></span>Etat des absences dans mon &eacute;quipe</h2>
            <div class="actions pull-right">
              <a href="" class="div_responsable_conges_open" >
                <button type="button" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;Déclarer une absence d'un employé de mon équipe</button>
              </a>
            </div>
          </div>
          <div class="box-content">
            <!-- La légende -->
            <table style="margin-bottom:20px !important">
              <tr>
    <?php
    foreach(array_merge($type_absences_perso, $type_absences_responsable, $type_absences_rh) as $type)
    {
        ?>
                <td class="<?php echo $type ?>" style="width:25px"></td><td>&nbsp;&nbsp;<?php echo $_absences[$type] ?></td><td style="width:25px"></td>
        <?php
    }
    ?> 
              </tr>
            </table>
            <!-- La navigation du calendrier -->
            <table class="calendrier">
              <thead><tr>
                <th style="width:42.5%; text-align:right;"><a class="prev" href="<?php echo $_SERVER['PHP_SELF'] ?>?page=responsable_equipe&month=<?php echo date('m', strtotime('-1 month', strtotime($year.'-'.$month.'-01'))) ?>&year=<?php echo date('Y', strtotime('-1 month', strtotime($year.'-'.$month.'-01'))) ?>"><<</a></th>
                <th style="width:15%; text-align:center;"><span class="title"><?php echo Calendrier::$month['fr'][$month] .' '. $year ?></span></th>
                <th style="width:42.5%; text-align:left;"><a class="next" href="<?php echo $_SERVER['PHP_SELF'] ?>?page=responsable_equipe&month=<?php echo date('m', strtotime('+1 month', strtotime($year.'-'.$month.'-01'))) ?>&year=<?php echo date('Y', strtotime('+1 month', strtotime($year.'-'.$month.'-01'))) ?>">>></a></th>
              </tr></thead>
            </table>
            <!-- Les absences de chaque employe de l'equipe -->
<?php
// premiere boucle sur toutes les equipes de l'employe
foreach($employes_a_valider_absences as $equipe => $employes_absences)
{
    ?>

            <table class="table table-striped table-bordered bootstrap-datatable datatable table-hover">
              <caption><span class="label label-primary" >Equipe <?php echo $equipe;?></span></caption>
              <thead>
                <tr>
                  <th style="width:15%"></th>
    <?php
    for( $j=1; $j<=$days_in_month; $j++ )
    {
        $type_jour = date('N',strtotime($year.'-'.$month.'-'.$j));
        $jour_class = '';
        if (in_array(strtotime($year.'-'.$month.'-'.$j), Openpap_Absence::getHolidays($year)))
        //if (Calendrier::joursFeries(strtotime($year.'-'.$month.'-'.$j)))
            $jour_class = 'ferie';
        if (strtotime($year.'-'.$month.'-'.$j) == strtotime(date('Y-m-d')))
            $jour_class = 'aujourdhui';
        ?>
                  <th class="<?php echo Calendrier::$weekdayXShort['fr'][$type_jour] ;?> <?php echo $jour_class ;?>" style="text-align:center;"><?php echo Calendrier::$weekdayXShort['fr'][$type_jour] ; ?> </th>
        <?php
    }
    ?>

                </tr>
              </thead>
              <tbody>

    <?php
    // deuxieme boucle sur les employe de chaque equipe
    foreach ($employes_absences as $employe_absences)
    {
        ?>
                <tr style="<?php echo ($employe_absences['id'] == $employes_id) ? 'font-weight: bold ; color: #030' : '' ?>"> 
                  <td><strong><?php echo $employe_absences['nom'] .' '. $employe_absences['prenom'];?></strong></td>
        <?php
        for($j = 1 ; $j <= $days_in_month ; $j++)
        {
            $type_jour = date('N', strtotime($year .'-'. $month .'-'. $j));

            // Sur ce calendrier on presente les absences de l'equipe sans indiquer le motif (sauf dans le cas de travail a distance). On indique seulement si l'absence est posée ou validée
            $couleurs_journee = array('matin' => 'transparent', 'apres_midi' => 'transparent') ;

            if(array_key_exists(date('Y-m-d', strtotime($year.'-'.$month.'-'.$j)), $employe_absences['absences']))
            {
                foreach($employe_absences['absences'][date('Y-m-d', strtotime($year.'-'.$month.'-'.$j))] as $demi_journee => $absences_jour)
                {
                    foreach ($absences_jour as $type => $absences_etat)
                    {
                        $couleurs_journee[$demi_journee] = $colors[$type] ;
                    }
                }
            }

            // On rejoute une couleur pour les jours feries et le jour en cours (si jour ferié on n'indique pas la couleur de l'absence)
            $jour_class = '' ;
            if (in_array(strtotime($year.'-'.$month.'-'.$j), Openpap_Absence::getHolidays($year)))
            //if (Calendrier::joursFeries(strtotime($year.'-'.$month.'-'.$j)))
            {
                $jour_class = 'ferie' ;
                $couleurs_journee = array('matin' => 'transparent', 'apres_midi' => 'transparent') ;
            }
            if (strtotime($year.'-'.$month.'-'.$j) == strtotime(date('Y-m-d')))
                $jour_class = 'aujourdhui';
            ?>
                  <td class="<?php echo $jour_class ;?> <?php echo Calendrier::$weekdayXShort['fr'][$type_jour] ; ?>" style="text-align:center; background: linear-gradient(to bottom right, <?php echo $couleurs_journee['matin'] ;?> 50%, <?php echo $couleurs_journee['apres_midi'] ;?> 51%); "><?php echo $j ;?></td>
            <?php
        }
        ?>
                </tr>
        <?php
    }
    ?> 
              </tbody>
            </table>

    <?php
}
?>

          </div>
        </div>
      </div>

<!-- FIN LES ABSENCES DE MON/MES EQUIPE --> 

      </div>
    </div>
